saveExact: true

packages:
  - apps/*
  - packages/*

allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  sharp: true

catalog:
  "@types/node": "25.9.1"
  "@types/react": "19.2.15"
  "@types/react-dom": "19.2.3"
  tsdown: "0.22.1"
  turbo: "2.9.16"
  typescript: "6.0.3"
  vite: "8.0.14"
  vitest: "4.1.7"

minimumReleaseAgeExclude:
  - react
  - react-dom
  - typescript
  - vite
  - "@vitejs/*"
  - turbo
  - "@turbo/*"
  - drizzle-orm
  - drizzle-kit
